
en:
  languageCode: en-us
  contentDir: content/en
ru: 
  languageCode: ru-ru
  contentDir: content/ru
  menu: 
    main:
      - name: Обо мне
        url: '#about'
        weight: 10      
      - name: Посты
        url: '#posts'
        weight: 20
      - name: Контакты
        url: '#contact'
        weight: 30
      
        
